### ISSUE TITLE
segfault on playing audio too fast

### ISSUE THREAD

**Issue by wahlao** [crumblingstatue/NoLifeExplorer#3]
playing audio too fast will crash due to a segfault 11.
reproduce by holding down enter while on an audio node.

**Comment by crumblingstatue** [comment]
I do remember a heisenbug about audio playing randomly crashing, but unfortunately, I can't reproduce it, even by holding down enter.
Help in tracking down this bug would be much appreciated!

**Comment by crumblingstatue** [comment]
In d4c382a6d938af300843b5980ef737afcb8686b1, I fixed a signed/unsigned conversion overflow bug. It might have fixed this bug.

**Comment by wahlao** [comment]
Unfortunately, the error still occurs in d4c382a6d938af300843b5980ef737afcb8686b1 . Here's a youtube video of it happening on my system. https://www.youtube.com/watch?v=L6txtuUX8CA

**Comment by crumblingstatue** [comment]
According to your backtrace, it segfaults on the call to sf::SoundStream::stop() in AudioStream::open().

I don't know why that would cause a segfault. It could be an SFML bug, but I am unsure.
